HISTFILESIZE=10000000

export EDITOR=vi
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/local/jetty/bin:/usr/local/mongodb/bin:/opt/Qt/5.3/clang_64/bin:$PATH

set -o vi
bind -m vi-insert "\C-l":clear-screen

alias ..='cd ..'
alias .-='cd -'
alias c='clear'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias h='history'
alias j='jobs'
alias l='ls -alrt'
alias lr='ls -lR'
alias ld='find . -type d'
alias scp='rsync -v -h --stats'
alias up='uptime'

function s() {
  ssh root@sdath$1
}

function test() {
  ssh srichardson@test
}

function web1() {
  ssh srichardson@web1
}

function web2() {
  ssh srichardson@web2
}
